name: Hello World

on:
  schedule:
    # Runs at 12:00 UTC (noon) every day
    - cron: "0 12 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    steps:
      - name: 21f1006867@ds.study.iitm.ac.in
        run: echo "Hello, world!"