name: Hello World

on: push  # Trigger the workflow on a push event

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the runner environment
    steps:
      - name: Say Hello
        run: echo "Hello, world!"